version: "3"
services:
  static-serve:
    build: '.'
    image: archive_static-serve
    container_name: archive_static-serve
    restart: unless-stopped
    ports:
      - ${PORT}:5000
    volumes:
      - ./data/${ARCHIVENAME}:/app/data/${ARCHIVENAME}
      - ./data/sitemap.json:/app/data/sitemap.json