version: "3"
services:
  static_serve:
    build: '.'
    image: archive-static_serve
    container_name: archive-static_serve
    restart: unless-stopped
    ports:
      - ${PORT}:5000
    volumes:
      - ./data:/app/data